### ISSUE TITLE
Summary: Exceeds Expectations

### ISSUE THREAD

**Issue by melissamcewen** [KarlGoddard/colmar#2]
Hi Karl, I'm reviewing for codecademy. Sorry about the assets issue, I will follow up on that. You did a great job giving it your own style and adding fonts. 

I have a few pointers I'm filing as "issues." Hopefully you find them helpful.

Overall great job! I hope you enjoyed making this and will make lots of cool websites like it in the future!

**Comment by KarlGoddard** [comment]
Thank you Melissa.  Very useful, I appreciate the advice on future issues with image sizing (use a container) and the margin issue (use min or max-width with caution).  Thank you for the grade, I've very pleased with that - it couldn't have been too bad then :-) Kind regards, Karl
